services:
    bot:
        container_name: tg-link-keeper-bot
        build: .
        restart: unless-stopped
        environment:
            - TELEGRAM_SUPER_USERS=${TELEGRAM_SUPER_USERS}
            - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
            - LINK_STORE_URL=${LINK_STORE_URL}
