services:
    bot:
        container_name: tg-link-keeper-bot
        image: ghcr.io/pkarpovich/tg-link-keeper-bot:latest
        restart: unless-stopped
        expose:
            - 8080
        environment:
            - TELEGRAM_SUPER_USERS=${TELEGRAM_SUPER_USERS}
            - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
            - LINK_STORE_URL=${LINK_STORE_URL}
        networks:
            - proxy
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.tg-link-keeper-bot.rule=Host(`${DOMAIN}`)"
            - "traefik.http.routers.tg-link-keeper-bot.entrypoints=web-secure"
            - "traefik.http.routers.tg-link-keeper-bot.tls.certresolver=le"

networks:
    proxy:
        external: true